
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 butterfly.gltf --transform --types
-->




    <script lang="ts">
				
	
import type * as THREE from 'three'
	
  import type { Snippet } from 'svelte'
        import { T, type Props } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        }: Props<THREE.Group> &  {
          ref?: THREE.Group
          children?: Snippet<[{ ref: THREE.Group }]>
          fallback?: Snippet
          error?: Snippet<[{ error: Error }]>
        } = $props()

				

				

        type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh,Cube1: THREE.Mesh,Extrude: THREE.Mesh,Extrude_1: THREE.Mesh
      
    }
    materials: {
      ['default']: THREE.MeshStandardMaterial
    }
  }

        const gltf = useGltf<GLTFResult>('/glb/butterfly.glb')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials['default']} rotation={[Math.PI / 2, 0, 0,]} />
<T.Mesh geometry={gltf.nodes.Cube1.geometry} material={gltf.materials['default']} rotation={[Math.PI / 2, 0, 0,]} />
<T.Mesh geometry={gltf.nodes.Extrude.geometry} material={gltf.materials['default']} rotation={[Math.PI / 2, 0, 0,]} />
<T.Mesh geometry={gltf.nodes.Extrude_1.geometry} material={gltf.materials['default']} rotation={[Math.PI / 2, 0, 0,]} />

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	